In [0]:
from pyspark.sql import SQLContext
from pyspark.sql import SparkSession
from pyspark.sql.types import StructField,StructType,StringType,IntegerType,DateType,FloatType
import pyspark

In [0]:
SS = SparkSession.builder.getOrCreate()
SS1 = SparkSession.builder.appName('New').getOrCreate()

In [0]:
new_df = SS.read.table('appl_stock_csv')
df_sql = SS1.sql('select * from appl_stock_csv')
#Loading table using SQL query

In [0]:
new_df.show(5)

In [0]:
df_sql.show(5)

In [0]:
new_df.printSchema()

In [0]:
######## Displaying a column, displaying a row, creating new column, filtering data using SQL using existing dataframe #######

In [0]:
new_df.select('Open').show(5)

In [0]:
new_df.select(['Open','Close']).show(5)

In [0]:
new_df.head(10)[1]

In [0]:
new_df.withColumn('Open+2',new_df['Open']+2).show(5)

In [0]:
new_df = new_df.withColumn('Open+2',new_df['Open']+2)

In [0]:
new_df = new_df.withColumnRenamed('Open+2','Open_2')

In [0]:
new_df.createOrReplaceTempView('Stock')

In [0]:
SS1.sql('select * from Stock').show(3)

In [0]:
SS1.sql('select * from Stock where Open >= 300').show(3)

In [0]:
####3. Filtering columns with single and multiple conditions, filter and collect to convert it to dictionary

In [0]:
new_df.filter('Open > 300').show(5)

In [0]:
new_df.filter((new_df['Open']>=309) & (new_df['Close']>=307)).show(5)

In [0]:
new_df.filter((new_df['Open']>300) & (new_df['High']>300)).select(['High','Close']).show(5)

In [0]:
x = new_df.filter(new_df['Open']>=200).select(['Date','Volume','Open']).collect()[1].asDict()

In [0]:
x['Volume']

In [0]:
df = SS1.read.table('sales_info')
#Read data directly from a table

df1 = SS1.sql('select * from sales_info')
#read data using SQL query

In [0]:
df1 = df1.withColumn('Sales',df1['Sales'].cast(IntegerType()))

In [0]:
df1.printSchema()

In [0]:
df1.groupBy('Company').mean().show()

In [0]:
df1.agg({'Sales':'sum'}).show()

In [0]:
from pyspark.sql.functions import countDistinct,avg,stddev,format_number

df1.select(countDistinct('sales')).show()

In [0]:
df1.select(avg('Sales').alias('Average_sales')).show()

In [0]:
df1.select(format_number(avg('Sales'),2).alias("Average_Sales")).show()

In [0]:
df1.orderBy('Sales').show()

In [0]:
df1.orderBy('Sales',ascending=False).show()

In [0]:
df1.orderBy(df1['Sales'].desc()).show()

In [0]:
ss2 = spark.builder.appName("New").getOrCreate()
df3 = ss2.read.csv("/FileStore/tables/ContainsNull.csv",inferSchema=True,header=True)

In [0]:
df3.printSchema()

In [0]:
df3.na.drop().show()

In [0]:
df3.na.drop(thresh=2).show()

In [0]:
df3.na.fill('Noname').show()

In [0]:
from pyspark.sql.functions import mean
mean_val = df3.select(mean('Sales')).collect()[0][0]

In [0]:
df3.fillna(mean_val,subset=['Sales']).show()

In [0]:
df3.na.fill(df3.select(mean('Sales')).collect()[0][0],['Sales']).show()

In [0]:
from pyspark.sql.functions import year,month,weekofyear,dayofmonth,dayofweek,date_format,dayofyear
new_df.select([dayofyear('Date'),'Open']).show(5)

In [0]:
new_df.select([month('Date'),'Open']).show(5)

In [0]:
new = new_df.select([year('Date').alias('Year'),'Open'])

In [0]:
new.filter(new['Open']>230).show()